### ISSUE TITLE
META: Still left for Final Launch

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#62]
- [x] Accordion boxes #17 
- [x] Registration Bar on Homepage #38 
- [x] Clean up blog page and landing 
- [x] Fix the spacing between the options on Experience Israel With Israel With Your Campus #34
- [x] Testimonials extending too far down in smaller browsers #7 
- [x] Search results page #19 
- [x] Height of banner on share the gift
- [x] Small fixes to sample itinerary #44 
- [x]  New page #59
- [x] Pay It Forward page (Needs to link to updated page)
- [x] Packing list needs to be able to be uploaded
- [x] Aspergers Itinerary needs to be able to be uploaded
- [x] Subscribe bar needs to be linked to Mailing List
- [x] Consistent Side Bar

**Comment by IshaDakota** [comment]
@Shorashim What is the link for the mailing list?

**Comment by Shorashim** [comment]
Do we need a separate page for this or can we link from MailChimp?

**Comment by IshaDakota** [comment]
please say let's link to mailchimp! We would need a page design for this otherwise.

**Comment by Shorashim** [comment]
https://us4.admin.mailchimp.com/lists/advanced-forms/subscribe/preview?id=133417

Is this what we link to? Can/should this be edited? Is there another option?

**Comment by IshaDakota** [comment]
I don;t see a form here.

**Comment by Shorashim** [comment]
To keep things consistent, can we have it link to the pop-up or does that not work? If not, what do I need to send you from MailChimp to make sure it's the right form?

Thanks!

**Comment by IshaDakota** [comment]
definitely,  don't thnk I have access to mail chimp - isn't there a link to the subsciprion form?

**Comment by Shorashim** [comment]
![screen shot 2015-08-11 at 11 37 38 am](https://cloud.githubusercontent.com/assets/13404688/9203540/6b00ec9a-401d-11e5-9a46-4c9bad175777.png)
This is what shows up, but I want to edit it. I also don't want it to be the form that's on our current website, since it won't match the branding. Any ideas?

**Comment by IshaDakota** [comment]
I think we should create a separate page with a signup form embedded. Unfortunately, that's anther step. Alternatively we could delete this form and link to a generic form.

**Comment by Shorashim** [comment]
That works. What do you need from me to make that happen?

**Comment by IshaDakota** [comment]
I actually found my password to mailchimp - ill poke around. Just to confirm, you are OK with deleting this form? I think you need to do that to create a generic one.

**Comment by Shorashim** [comment]
Will it delete our list? I definitely don't want to delete the interest list. I am okay making a new form if it doesn't delete that. Let me know!

**Comment by IshaDakota** [comment]
no - it will only delete the form

**Comment by Shorashim** [comment]
Totally fine with that then!

**Comment by IshaDakota** [comment]
It's too complicated for me to make a new form.... the only option is to make a separate badge with the embedded form. There's no design for this - Ill have to wing it.

**Comment by Shorashim** [comment]
Oh jeez. I am sorry. Are you able to work off the form on the homepage? Do you want me to get a design from them?

**Comment by IshaDakota** [comment]
taking it back... I think I can edit the form on mail chimp.... can you edit the text that goes above? Pasted below:

Mark your calendars! Registration for Winter 2013-14 will open on September 10, 2013 for new registrants and on September 9, 2013 for returning applicants.

By entering your information below, you will receive advance notification of the opening of registration, and details on how to apply for a program this winter.

Your email address will only be used to correspond with you about Taglit-Birthright Israel registration for the winter.

Providing information below does not automatically register you, or guarantee your space on the program. We will send you an email when the Taglit-Birthright Israel registration opens, so that you can submit your application, deposit, and all other documentation at that time.

**Comment by IshaDakota** [comment]
This is the link:
http://eepurl.com/ymSBv

**Comment by Shorashim** [comment]
Mark your calendars: Registration for Winter 2015/2016 will open on September 8, 2015. In the meantime, you can pre-register for trips between now and August 2016 at bit.ly/ShorashimPreRegisterNow.

You can also enter your information below for additional updates on pre-registration, registration, and future trips.

**Comment by Shorashim** [comment]
@IshaDakota Pay It Forward is still linking to the old page. The domain needs to link to the new Pay It Forward page

**Comment by Shorashim** [comment]
@IshaDakota Logos also need to be aligned correctly. Won't let me add to initial comment

**Comment by IshaDakota** [comment]
> Pay It Forward is still linking to the old page. The domain needs to link to the new Pay It Forward page

When we redirect the site this will change... it doesn't need to be updated here.

**Comment by Shorashim** [comment]
Ok thanks

**Comment by Shorashim** [comment]
Added consistent sidebar

**Comment by IshaDakota** [comment]
> Added consistent sidebar

Dont know what that means

**Comment by Shorashim** [comment]
Adding** sorry was also super tired. The side bar is not consistent across all pages.

**Comment by Shorashim** [comment]
I put that on the list of pending things

**Comment by Shorashim** [comment]
The order should be Pre-register, then Pay It Forward, then mailing list, unless you disagree for some reason. 

![screen shot 2015-08-12 at 8 02 57 am](https://cloud.githubusercontent.com/assets/13404688/9224528/ad10e51c-40c8-11e5-9857-c2f7e4d6f2cd.png)
![screen shot 2015-08-12 at 8 03 09 am](https://cloud.githubusercontent.com/assets/13404688/9224531/af4c76ca-40c8-11e5-9110-9022ed52cc43.png)

The blog should have this under the search bar
![screen shot 2015-08-12 at 8 05 13 am](https://cloud.githubusercontent.com/assets/13404688/9224570/f9da8196-40c8-11e5-91ba-c05c2116ea39.png)

The actual Pay It Forward page does not need the Pay It Forward button, as it is redundant.

Please let me know if there is anything that I need to clarify

**Comment by IshaDakota** [comment]
no disagreement at all... i think I just follwed the PSDs and they were different on some pages.

I'll make them all uniform.

**Comment by Shorashim** [comment]
Thank you!

**Comment by IshaDakota** [comment]
Before I change all of these, I just want double confirmation:

The sidebar should be the same on EVERY page with the same order and the same items 

(except pay it forward which won't have that one and the blog which has a special one),

It wasn't in the design that way, so I just want to be sure.

**Comment by IshaDakota** [comment]
<img width="149" alt="about_us___site-install" src="https://cloud.githubusercontent.com/assets/688507/9226086/a20c10d8-40d2-11e5-9813-4415a62f8e79.png">

like this (ignore squished type - i zoomed far out)

**Comment by Shorashim** [comment]
Perfect!

**Comment by Shorashim** [comment]
Confirmed again. This sounds perfect to me.
