### ISSUE TITLE
Links For Parameter Tracking Through Reg Admin

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#91]
Pre-register pop-up: http://bit.ly/iwipreregisterpopup
Pre-register button on "How To Register" page: http://bit.ly/iwihowtoregisterpreregister
Pre-register link on MailChimp sign up: http://bit.ly/iwipreregistermailchimp

Will update as I create more. Working on the links today

**Comment by Shorashim** [comment]
Pre-register button on side: http://bit.ly/iwipreregistersidebar

**Comment by Shorashim** [comment]
Pre-register link on countdown bar: http://bit.ly/PreRegisterCountdown

**Comment by IshaDakota** [comment]
Hard Coded (Adam)
- [ ] Pre-register pop-up: http://bit.ly/iwipreregisterpopup <-- Do you mean the green button on the side?
- [ ] Pre-register link on countdown bar: http://bit.ly/PreRegisterCountdown

Editable (Lauren)
- [ ] Pre-register button on "How To Register" page: http://bit.ly/iwihowtoregisterpreregister
- [ ] Pre-register link on MailChimp sign up: http://bit.ly/iwipreregistermailchimp
- [ ] Pre-register button on side: http://bit.ly/iwipreregistersidebar

**Comment by Shorashim** [comment]
@IshaDakota yes the green floater on the homepage

**Comment by Shorashim** [comment]
@IshaDakota where do I edit the sidebar on the new website?

**Comment by IshaDakota** [comment]
For the sidebar elements, there should be a gear dropdown to edit... no?

**Comment by Shorashim** [comment]
Yep! Didn't see that yesterday. Thanks!
